
server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB # 1개의 파일의 최대 사이즈
      max-request-size: 20MB # 전체 요청의 최대 사이즈

logging.level:
  org.hibernate.SQL: debug

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html

jwt:
  secret: 
kakao:
  client_id: 
  redirect_url: 
  client_secret: 
# 업로드 파일 저장 경로
upload:
  path: C:/todo_upload

# s3 접근 설정
aws:
  credentials:
    accessKey:
    secretKey:
  region: ap-northeast-2
  bucketName:




